name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  intl: ^0.19.0
  pull_to_refresh_flutter3: ^2.0.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

